import CustomError from '../../error/custom-error';
import { ComponentNotFound, MergeConflictOnRemote } from '../exceptions';
import ActionNotFound from '../exceptions/action-not-found';
import ClientIdInUse from '../exceptions/client-id-in-use';
import ServerIsBusy from '../exceptions/server-is-busy';
import { OldClientVersion, PermissionDenied, RemoteScopeNotFound, UnexpectedNetworkError } from './exceptions';
import ExportAnotherOwnerPrivate from './exceptions/export-another-owner-private';
export declare function remoteErrorHandler(code: number, parsedError: Record<string, any>, remotePath: string, err: any): ComponentNotFound | MergeConflictOnRemote | OldClientVersion | PermissionDenied | RemoteScopeNotFound | UnexpectedNetworkError | ExportAnotherOwnerPrivate | CustomError | ActionNotFound | ClientIdInUse | ServerIsBusy;
